name: gurbani_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  # sdk: '>=3.1.0 <4.0.0'
   sdk: '>=2.18.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  archive: ^3.4.4
  animated_text_kit: ^4.2.2
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.9.0
  flutter_isolate: ^2.0.4
  flip_card: ^0.7.0
  flip_widget: ^0.1.11

#  get_it: ^7.6.4
  go_router: ^11.1.2
  gurmukhi_utils:
  google_fonts: 6.1.0
  lottie: ^1.4.1
  sqflite: ^2.3.0  
  path_provider: ^2.0.15  
#  permission_handler: ^11.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

    - assets/database.zip
    - assets/images/
    - assets/lottiee/tick.json
    - assets/lottiee/timeslotanim.json

  fonts:
    #NotoSans Gurmukhi Font Family...
    - family: Gurmukhi-Bold
      fonts:
        - asset: assets/fonts/Gurmukhi-Bold.ttf

    - family: Gurmukhi-Medium
      fonts:
        - asset: assets/fonts/Gurmukhi-Medium.ttf

    - family: Gurmukhi-Regular
      fonts:
        - asset: assets/fonts/Gurmukhi-Regular.ttf

    - family: AnmolUni
      fonts:
        - asset: assets/fonts/AnmolUni.ttf

    #Montserrat Font Family...
    - family: Montserrat-Regular
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf

    - family: Montserrat-Bold
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf


    - family: Montserrat-ExtraBold
      fonts:
        - asset: assets/fonts/Montserrat-ExtraBold.ttf

    - family: Montserrat-Light
      fonts:
        - asset: assets/fonts/Montserrat-Light.ttf